language: python

python:
    - "2.7"

sudo: false  # Use container-based infrastructure
cache:
  directories:
    - $HOME/.cache/pip  # cache pip requirements
services:
  - mongodb

env:
  # Flask configurations
  - HOST='0.0.0.0'
  - PORT='5000'
  - DEBUG='TRUE'
  - SECRET_KEY='abc123'
  - CSRF_SESSION_KEY='abc123'

  # Google+, Google Auth, and Google Calendar configurations
  - EVENTUM_GOOGLE_AUTH_ENABLED='FALSE'
  - EVENTUM_INSTALLED_APP_CLIENT_SECRET_PATH='config/installed_app_client_secrets.json'
  - EVENTUM_INSTALLED_APP_CREDENTIALS_PATH='config/installed_app_credentials.json'
  - EVENTUM_CLIENT_SECRETS_PATH='config/client_secrets.json'
  - EVENTUM_PRIVATE_CALENDAR_ID='a@group.calendar.google.com'
  - EVENTUM_PUBLIC_CALENDAR_ID='b@group.calendar.google.com'

before_install:
  # Install SCSS
  - gem install sass
install:
  - pip install -r config/requirements.txt
  - pip install flake8

before_script:
  - flake8 app/
  - flake8 script/
  - flake8 config
  - flake8 test/
  - mkdir log
script:
  - nosetests

